<?php

declare(strict_types=1);

namespace App\Privacy;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use PrivacyCI\Lifecycle\DeletionRequest;
use PrivacyCI\Lifecycle\SubjectDeleter;

/**
 * Generated by `php artisan privacy:make-handler` from your privacy policy.
 *
 * Review it before merging, and own it afterwards, this file is yours.
 * Regenerating overwrites it, so once you have edited it by hand, keep
 * editing by hand.
 *
 * Order matters. Rows furthest from the user go first and the
 * user's own row goes last, so foreign keys stay satisfied throughout.
 * Non-database stores are cleared before any row is touched, because once
 * the row is gone its key pattern can no longer be resolved.
 */
final class DeleteUser implements SubjectDeleter
{
    public function delete(DeletionRequest $request): void
    {
        $subjectId = $request->subjectId;

        // inferred by static analysis, confirm this key before relying on it
        Storage::disk('local')->delete("avatars/{$subjectId}.png");

        // inferred by static analysis, confirm this key before relying on it
        Cache::forget("user:{$subjectId}");

        // Terminates because actor_id is among the columns being nulled,
        // so the next pass matches nothing. Keep it that way if you edit this.
        do {
            $affected = \App\Models\AuditEntry::query()
                ->where('actor_id', $subjectId)
                ->limit(1000)
                ->update([
                    'actor_id' => null,
                ]);
        } while ($affected > 0);

        // Terminates because user_id is among the columns being nulled,
        // so the next pass matches nothing. Keep it that way if you edit this.
        do {
            $affected = \App\Models\Comment::query()
                ->where('user_id', $subjectId)
                ->limit(1000)
                ->update([
                    'author_ip' => null,
                    'user_id' => null,
                ]);
        } while ($affected > 0);

        do {
            $deleted = DB::table('legacy_profiles')
                ->where('user_id', $subjectId)
                ->limit(1000)
                ->delete();
        } while ($deleted > 0);

        // Terminates because user_id is among the columns being nulled,
        // so the next pass matches nothing. Keep it that way if you edit this.
        do {
            $affected = \App\Models\Order::query()
                ->where('user_id', $subjectId)
                ->limit(1000)
                ->update([
                    'user_id' => null,
                ]);
        } while ($affected > 0);

        // no foreign key to the subject; supply the lookup yourself
        // TODO: password_reset_tokens (DELETE)

        do {
            $deleted = DB::table('recommendation_events')
                ->where('user_id', $subjectId)
                ->limit(1000)
                ->delete();
        } while ($deleted > 0);

        do {
            $deleted = DB::table('sessions')
                ->where('user_id', $subjectId)
                ->limit(1000)
                ->delete();
        } while ($deleted > 0);

        \App\Models\User::query()->whereKey($subjectId)->delete();

        // TODO: these locations have no policy and are therefore untouched.
        // Classify them in your privacy policy and regenerate.
        //   - comments.body
        //   - orders.shipping_address
    }
}
