<?php

declare(strict_types=1);

namespace App\Privacy;

use App\Models\User;
use PrivacyCI\Policy\PrivacyPolicy;

/**
 * Generated by `php artisan privacy:make-policy`.
 *
 * Every rule below is commented out on purpose. Discovery suggests; you
 * decide. Uncommenting a line is a decision to act on that data,
 * `privacy:make-handler` turns these into real deletion code, so read
 * each one before enabling it.
 *
 *   delete()     remove it entirely
 *   anonymize()  keep the row, drop the link and the identifiers
 *   retain()     keep it, with a documented reason (required)
 *   ignore()     not personal data, with a documented reason (required)
 *   custom()     your own handler class
 *
 * Anything left unclassified keeps failing `privacy:check`, which is the
 * point: an undecided location is not the same as a harmless one.
 */
final class UserPrivacyPolicy extends PrivacyPolicy
{
    public function configure(): void
    {
        $this->subject(User::class);

        // ── orders ──────────────────────────────────── no link to the subject
        //    shipping_address              0.80  contact detail

        // No foreign key to the subject, so a generated handler cannot look these
        // rows up. Supply the lookup yourself, or rule the table out:
        // $this->custom(Order::class, \App\Privacy\PurgeTheseRows::class);
        // $this->ignore(Order::class)->reason("");

        // ── comments ────────────────────────────────── no link to the subject
        //    body                          0.40  free text may embed personal data

        // No foreign key to the subject, so a generated handler cannot look these
        // rows up. Supply the lookup yourself, or rule the table out:
        // $this->custom(Comment::class, \App\Privacy\PurgeTheseRows::class);
        // $this->ignore(Comment::class)->reason("");
    }
}
